steps:

  # 依存関係のインストール
  - name: 'node:24-slim'
    entrypoint: npm
    args: ['ci']

  # Discordコマンド登録
  - name: 'node:24-slim'
    entrypoint: node
    args: ['scripts/deployCommands.js']
    secretEnv: 
      - DISCORD_TOKEN
      - DISCORD_APP_ID
      - DISCORD_GUILD_ID

  #Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/discord-taskbot-image:$COMMIT_SHA', '.']

  #Artifact RefistryへPush
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/discord-taskbot-image:$COMMIT_SHA']

  #Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
    - run
    - deploy
    - discord-task-bot
    - --image
    - asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/discord-taskbot-image:$COMMIT_SHA
    - --region
    - asia-northeast1
    - --platform
    - managed
    - --quiet

images:
  - asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/discord-taskbot-image:$COMMIT_SHA

timeout: 500s
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DISCORD_TOKEN/versions/latest
      env: DISCORD_TOKEN

    - versionName: projects/$PROJECT_ID/secrets/DISCORD_APP_ID/versions/latest
      env: DISCORD_APP_ID

    - versionName: projects/$PROJECT_ID/secrets/DISCORD_GUILD_ID/versions/latest
      env: DISCORD_GUILD_ID